services:
  tea-backend:
    # image: nikitaikonkin/tea-taste-api
    container_name: tea-backend
    build: .
    # ports:
    #   - 3001:3001
    env_file:
      - .env
    volumes:
      - ./.env:/app/.env
    networks:
      - mynetwork

networks:
  mynetwork:
    external: true