version: "3"
services:
  app:
    build: .
    ports:
      - "3001:3001"
    # volumes:
    #   - .:/app
    #   - /app/node_modules
    # env_file:
    #   - .env
  # volumes:
  #   - /etc/letsencrypt:/etc/letsencrypt
