// Aroma and taste vocabulary, translated.
//
// ─────────────────────────────────────────────────────────────────────────────
// MIRRORED IN THE FRONTEND at tea-taste-frontend/src/i18n/descriptors.js.
// Change both.
// Pure data, no logic — this copy is what controllers/render.js uses to render
// a tasting in English or Chinese for a crawler. Same reason as utils/formMeta.js:
// two repositories, two images, and a shared package is not worth it for a table.
//
// The table below must stay byte-identical to the frontend copy; tests/i18n.test.js
// asserts the key set and the translations match when both trees are present.
// ─────────────────────────────────────────────────────────────────────────────
//
// **The Russian string is the key, and it is the stored value.** Every Aroma and
// Taste document holds its descriptor as literal Russian text
// (`aromaStage1: "Цветочный"`), and the seeder says so in as many words: the
// dictionary may only be added to, never renamed, or existing tastings lose
// their match. So nothing here migrates data — translation is a lookup at
// display time, and a term with no entry falls back to the Russian, which is
// exactly what the site showed before.
//
// Covers the merged aroma + taste vocabulary (391 terms; 104 appear in both
// lists and translate identically either way).

const DESCRIPTORS = {
    // ── Fruit ────────────────────────────────────────────────────────────────
    'Абрикос': { en: 'Apricot', zh: '杏' },
    'Ананас': { en: 'Pineapple', zh: '菠萝' },
    'Апельсин': { en: 'Orange', zh: '橙' },
    'Брусника': { en: 'Lingonberry', zh: '越橘' },
    'Вишня': { en: 'Cherry', zh: '樱桃' },
    'Грейпфрут': { en: 'Grapefruit', zh: '西柚' },
    'Гуава': { en: 'Guava', zh: '番石榴' },
    'Ежевика': { en: 'Blackberry', zh: '黑莓' },
    'Зелёное яблоко': { en: 'Green apple', zh: '青苹果' },
    'Изюм': { en: 'Raisin', zh: '葡萄干' },
    'Инжир': { en: 'Fig', zh: '无花果' },
    'Клубника': { en: 'Strawberry', zh: '草莓' },
    'Клюква': { en: 'Cranberry', zh: '蔓越莓' },
    'Кожура винограда': { en: 'Grape skin', zh: '葡萄皮' },
    'Косточковый': { en: 'Stone fruit', zh: '核果' },
    'Косточковый фрукт': { en: 'Stone fruit', zh: '核果' },
    'Курага': { en: 'Dried apricot', zh: '杏干' },
    'Лайм': { en: 'Lime', zh: '青柠' },
    'Лимон': { en: 'Lemon', zh: '柠檬' },
    'Личи': { en: 'Lychee', zh: '荔枝' },
    'Малина': { en: 'Raspberry', zh: '树莓' },
    'Манго': { en: 'Mango', zh: '芒果' },
    'Мандарин': { en: 'Mandarin', zh: '柑橘' },
    'Маракуйя': { en: 'Passion fruit', zh: '百香果' },
    'Незрелый хурма': { en: 'Unripe persimmon', zh: '生柿子' },
    'Нектарин': { en: 'Nectarine', zh: '油桃' },
    'Папайя': { en: 'Papaya', zh: '木瓜' },
    'Персик': { en: 'Peach', zh: '桃' },
    'Помело': { en: 'Pomelo', zh: '柚子' },
    'Ревень': { en: 'Rhubarb', zh: '大黄' },
    'Слива': { en: 'Plum', zh: '李子' },
    'Смородина': { en: 'Blackcurrant', zh: '黑加仑' },
    'Спелый манго': { en: 'Ripe mango', zh: '熟芒果' },
    'Сушёное яблоко': { en: 'Dried apple', zh: '苹果干' },
    'Сушёный инжир': { en: 'Dried fig', zh: '无花果干' },
    'Сушёный фрукт': { en: 'Dried fruit', zh: '果干' },
    'Финик': { en: 'Date', zh: '枣' },
    'Фруктовая сладость': { en: 'Fruit sweetness', zh: '果甜' },
    'Фруктовый': { en: 'Fruity', zh: '果香' },
    'Черешня': { en: 'Sweet cherry', zh: '甜樱桃' },
    'Черника': { en: 'Blueberry', zh: '蓝莓' },
    'Чернослив': { en: 'Prune', zh: '西梅' },
    'Юзу': { en: 'Yuzu', zh: '柚子（日本）' },
    'Яблочная кислота': { en: 'Apple acidity', zh: '苹果酸' },
    'Яблочный': { en: 'Apple', zh: '苹果' },
    'Ягодный': { en: 'Berry', zh: '莓果' },
    'Запечённое яблоко': { en: 'Baked apple', zh: '烤苹果' },
    'Тропический': { en: 'Tropical', zh: '热带水果' },
    'Цедра цитрусовых': { en: 'Citrus zest', zh: '柑橘皮' },
    'Цитрусовый': { en: 'Citrus', zh: '柑橘' },
    'Бергамот': { en: 'Bergamot', zh: '佛手柑' },

    // ── Floral ───────────────────────────────────────────────────────────────
    'Цветочный': { en: 'Floral', zh: '花香' },
    'Жасмин': { en: 'Jasmine', zh: '茉莉' },
    'Жасминовый': { en: 'Jasmine', zh: '茉莉香' },
    'Зелёный жасмин': { en: 'Green jasmine', zh: '青茉莉' },
    'Лёгкий жасмин': { en: 'Light jasmine', zh: '淡茉莉' },
    'Насыщенный жасмин': { en: 'Rich jasmine', zh: '浓茉莉' },
    'Роза': { en: 'Rose', zh: '玫瑰' },
    'Розовый': { en: 'Rose', zh: '玫瑰香' },
    'Свежая роза': { en: 'Fresh rose', zh: '鲜玫瑰' },
    'Сухая роза': { en: 'Dried rose', zh: '干玫瑰' },
    'Дамасская роза': { en: 'Damask rose', zh: '大马士革玫瑰' },
    'Розовая вода': { en: 'Rose water', zh: '玫瑰水' },
    'Лаванда': { en: 'Lavender', zh: '薰衣草' },
    'Лавандовый': { en: 'Lavender', zh: '薰衣草香' },
    'Свежая лаванда': { en: 'Fresh lavender', zh: '鲜薰衣草' },
    'Сухая лаванда': { en: 'Dried lavender', zh: '干薰衣草' },
    'Ромашка': { en: 'Chamomile', zh: '洋甘菊' },
    'Фиалка': { en: 'Violet', zh: '紫罗兰' },
    'Пион': { en: 'Peony', zh: '牡丹' },
    'Османтус': { en: 'Osmanthus', zh: '桂花' },
    'Сладкий османтус': { en: 'Sweet osmanthus', zh: '甜桂花' },
    'Фруктовый османтус': { en: 'Fruity osmanthus', zh: '果香桂花' },
    'Лист одуванчика': { en: 'Dandelion leaf', zh: '蒲公英叶' },

    // ── Spice ────────────────────────────────────────────────────────────────
    'Пряный': { en: 'Spicy', zh: '辛香' },
    'Корица': { en: 'Cinnamon', zh: '肉桂' },
    'Коричная палочка': { en: 'Cinnamon stick', zh: '桂皮' },
    'Молотая корица': { en: 'Ground cinnamon', zh: '肉桂粉' },
    'Гвоздика': { en: 'Clove', zh: '丁香' },
    'Гвоздичный бутон': { en: 'Clove bud', zh: '丁香花蕾' },
    'Молотая гвоздика': { en: 'Ground clove', zh: '丁香粉' },
    'Сушёная гвоздика': { en: 'Dried clove', zh: '干丁香' },
    'Эфирное масло гвоздики': { en: 'Clove essential oil', zh: '丁香精油' },
    'Имбирь': { en: 'Ginger', zh: '姜' },
    'Имбирный': { en: 'Ginger', zh: '姜香' },
    'Свежий имбирь': { en: 'Fresh ginger', zh: '鲜姜' },
    'Сушёный имбирь': { en: 'Dried ginger', zh: '干姜' },
    'Карамелизированный имбирь': { en: 'Candied ginger', zh: '糖渍姜' },
    'Анис': { en: 'Anise', zh: '茴香' },
    'Звёздчатый анис': { en: 'Star anise', zh: '八角' },
    'Фенхель': { en: 'Fennel', zh: '小茴香' },
    'Кардамон': { en: 'Cardamom', zh: '豆蔻' },
    'Зелёный кардамон': { en: 'Green cardamom', zh: '绿豆蔻' },
    'Чёрный кардамон': { en: 'Black cardamom', zh: '黑豆蔻' },
    'Мускатный орех': { en: 'Nutmeg', zh: '肉豆蔻' },
    'Перец': { en: 'Pepper', zh: '胡椒' },
    'Перечный': { en: 'Peppery', zh: '胡椒味' },
    'Чёрный перец': { en: 'Black pepper', zh: '黑胡椒' },
    'Белый перец': { en: 'White pepper', zh: '白胡椒' },
    'Зелёный перец': { en: 'Green peppercorn', zh: '青胡椒' },
    'Розовый перец': { en: 'Pink peppercorn', zh: '粉红胡椒' },
    'Шафран': { en: 'Saffron', zh: '藏红花' },

    // ── Nut ──────────────────────────────────────────────────────────────────
    'Ореховый': { en: 'Nutty', zh: '坚果香' },
    'Орех': { en: 'Nut', zh: '坚果' },
    'Миндаль': { en: 'Almond', zh: '杏仁' },
    'Миндальный': { en: 'Almond', zh: '杏仁香' },
    'Сладкий миндаль': { en: 'Sweet almond', zh: '甜杏仁' },
    'Горький миндаль': { en: 'Bitter almond', zh: '苦杏仁' },
    'Жареный миндаль': { en: 'Roasted almond', zh: '烤杏仁' },
    'Фундук': { en: 'Hazelnut', zh: '榛子' },
    'Фундуковый': { en: 'Hazelnut', zh: '榛子香' },
    'Свежий фундук': { en: 'Fresh hazelnut', zh: '鲜榛子' },
    'Жареный фундук': { en: 'Roasted hazelnut', zh: '烤榛子' },
    'Кешью': { en: 'Cashew', zh: '腰果' },
    'Арахис': { en: 'Peanut', zh: '花生' },
    'Кокос': { en: 'Coconut', zh: '椰子' },
    'Кокосовый': { en: 'Coconut', zh: '椰香' },
    'Кокосовое молоко': { en: 'Coconut milk', zh: '椰奶' },
    'Сушёный кокос': { en: 'Dried coconut', zh: '椰丝' },
    'Кедровый орех': { en: 'Pine nut', zh: '松子' },
    'Жареный орех': { en: 'Roasted nut', zh: '烤坚果' },
    'Семя кунжута': { en: 'Sesame seed', zh: '芝麻' },
    'Марципан': { en: 'Marzipan', zh: '杏仁糖膏' },

    // ── Herb / grass ─────────────────────────────────────────────────────────
    'Травяной': { en: 'Herbal', zh: '草本' },
    'Мята': { en: 'Mint', zh: '薄荷' },
    'Мятный': { en: 'Minty', zh: '薄荷香' },
    'Перечная мята': { en: 'Peppermint', zh: '胡椒薄荷' },
    'Кудрявая мята': { en: 'Spearmint', zh: '留兰香' },
    'Яблочная мята': { en: 'Apple mint', zh: '苹果薄荷' },
    'Шалфей': { en: 'Sage', zh: '鼠尾草' },
    'Шалфейный': { en: 'Sage', zh: '鼠尾草香' },
    'Зелёный шалфей': { en: 'Green sage', zh: '青鼠尾草' },
    'Сушёный шалфей': { en: 'Dried sage', zh: '干鼠尾草' },
    'Тимьян': { en: 'Thyme', zh: '百里香' },
    'Эвкалипт': { en: 'Eucalyptus', zh: '桉树' },
    'Эвкалиптовый': { en: 'Eucalyptus', zh: '桉树香' },
    'Свежий эвкалипт': { en: 'Fresh eucalyptus', zh: '鲜桉叶' },
    'Эвкалиптовое масло': { en: 'Eucalyptus oil', zh: '桉树油' },
    'Мелисса': { en: 'Lemon balm', zh: '香蜂草' },
    'Сено': { en: 'Hay', zh: '干草' },
    'Сеновой': { en: 'Hay', zh: '干草味' },
    'Сухое сено': { en: 'Dry hay', zh: '干草' },
    'Свежескошенная трава': { en: 'Cut grass', zh: '青草' },
    'Трава после дождя': { en: 'Grass after rain', zh: '雨后青草' },
    'Травяная горечь': { en: 'Herbal bitterness', zh: '草本苦' },
    'Зелёный чай': { en: 'Green tea', zh: '绿茶' },
    'Чёрный чай': { en: 'Black tea', zh: '红茶' },
    'Иван-чай': { en: 'Fireweed', zh: '柳兰茶' },
    'Женьшень': { en: 'Ginseng', zh: '人参' },
    'Лекарственные травы': { en: 'Medicinal herbs', zh: '药草' },
    'Полынь': { en: 'Wormwood', zh: '艾草' },
    'Щавель': { en: 'Sorrel', zh: '酸模' },
    'Цикорий': { en: 'Chicory', zh: '菊苣' },
    'Лист смородины': { en: 'Currant leaf', zh: '黑加仑叶' },
    'Хвойная свежесть': { en: 'Conifer freshness', zh: '松针清香' },

    // ── Wood / resin ─────────────────────────────────────────────────────────
    'Древесный': { en: 'Woody', zh: '木香' },
    'Дуб': { en: 'Oak', zh: '橡木' },
    'Дубовый': { en: 'Oak', zh: '橡木香' },
    'Дубовая кора': { en: 'Oak bark', zh: '橡树皮' },
    'Сухой дуб': { en: 'Dry oak', zh: '干橡木' },
    'Копчёный дуб': { en: 'Smoked oak', zh: '烟熏橡木' },
    'Выдержанное в бочке': { en: 'Barrel-aged', zh: '桶陈' },
    'Сосна': { en: 'Pine', zh: '松' },
    'Смола сосны': { en: 'Pine resin', zh: '松脂' },
    'Сосновая смола': { en: 'Pine resin', zh: '松脂' },
    'Кедр': { en: 'Cedar', zh: '雪松' },
    'Кедровый': { en: 'Cedar', zh: '雪松香' },
    'Свежий кедр': { en: 'Fresh cedar', zh: '鲜雪松' },
    'Сухой кедр': { en: 'Dry cedar', zh: '干雪松' },
    'Древесина кедра': { en: 'Cedar wood', zh: '雪松木' },
    'Смола кедра': { en: 'Cedar resin', zh: '雪松脂' },
    'Сандал': { en: 'Sandalwood', zh: '檀香' },
    'Сандаловый': { en: 'Sandalwood', zh: '檀香' },
    'Бамбук': { en: 'Bamboo', zh: '竹' },
    'Берёза': { en: 'Birch', zh: '桦木' },
    'Кора': { en: 'Bark', zh: '树皮' },
    'Трухлявое дерево': { en: 'Rotten wood', zh: '朽木' },
    'Смолистый': { en: 'Resinous', zh: '树脂香' },
    'Ладан': { en: 'Frankincense', zh: '乳香' },
    'Мирра': { en: 'Myrrh', zh: '没药' },
    'Элеми': { en: 'Elemi', zh: '榄香脂' },
    'Амбра': { en: 'Amber', zh: '龙涎香' },
    'Прополис': { en: 'Propolis', zh: '蜂胶' },

    // ── Earth / mineral ──────────────────────────────────────────────────────
    'Землистый': { en: 'Earthy', zh: '土香' },
    'Мокрая земля': { en: 'Wet earth', zh: '湿土' },
    'Мокрая почва': { en: 'Wet soil', zh: '湿泥土' },
    'Сырая почва': { en: 'Raw soil', zh: '生土' },
    'Лесная земля': { en: 'Forest floor', zh: '林地' },
    'Влажный лес': { en: 'Damp forest', zh: '潮湿森林' },
    'После дождя': { en: 'After rain', zh: '雨后' },
    'Мох': { en: 'Moss', zh: '苔藓' },
    'Мшистый': { en: 'Mossy', zh: '苔藓味' },
    'Зелёный мох': { en: 'Green moss', zh: '青苔' },
    'Минеральный': { en: 'Mineral', zh: '矿物' },
    'Минеральная вода': { en: 'Mineral water', zh: '矿泉水' },
    'Минеральная соль': { en: 'Mineral salt', zh: '矿盐' },
    'Камень': { en: 'Stone', zh: '石' },
    'Каменный': { en: 'Stony', zh: '石感' },
    'Мокрый камень': { en: 'Wet stone', zh: '湿石' },
    'Сухой камень': { en: 'Dry stone', zh: '干石' },
    'Галька': { en: 'Pebble', zh: '卵石' },
    'Кремень': { en: 'Flint', zh: '燧石' },
    'Известняк': { en: 'Limestone', zh: '石灰岩' },
    'Графит': { en: 'Graphite', zh: '石墨' },
    'Металл': { en: 'Metal', zh: '金属' },
    'Металлический': { en: 'Metallic', zh: '金属味' },
    'Железо': { en: 'Iron', zh: '铁' },
    'Кровянистый металл': { en: 'Bloody metal', zh: '血腥金属味' },
    'Мокрый песок': { en: 'Wet sand', zh: '湿沙' },
    'Мокрый цемент': { en: 'Wet cement', zh: '湿水泥' },
    'Каменная соль': { en: 'Rock salt', zh: '岩盐' },
    'Гималайская соль': { en: 'Himalayan salt', zh: '喜马拉雅盐' },

    // ── Sweet / dairy ────────────────────────────────────────────────────────
    'Сладкий': { en: 'Sweet', zh: '甜' },
    'Мёд': { en: 'Honey', zh: '蜂蜜' },
    'Медовый': { en: 'Honey', zh: '蜜香' },
    'Цветочный мёд': { en: 'Flower honey', zh: '百花蜜' },
    'Липовый мёд': { en: 'Linden honey', zh: '椴树蜜' },
    'Гречишный мёд': { en: 'Buckwheat honey', zh: '荞麦蜜' },
    'Каштановый мёд': { en: 'Chestnut honey', zh: '栗子蜜' },
    'Карамель': { en: 'Caramel', zh: '焦糖' },
    'Карамельный': { en: 'Caramel', zh: '焦糖香' },
    'Мягкая карамель': { en: 'Soft caramel', zh: '软焦糖' },
    'Солёная карамель': { en: 'Salted caramel', zh: '海盐焦糖' },
    'Сливочная карамель': { en: 'Cream caramel', zh: '奶油焦糖' },
    'Жжёная карамель': { en: 'Burnt caramel', zh: '焦化糖' },
    'Ириска': { en: 'Toffee', zh: '太妃糖' },
    'Крем-брюле': { en: 'Crème brûlée', zh: '焦糖布丁' },
    'Сахар': { en: 'Sugar', zh: '糖' },
    'Сахарный сироп': { en: 'Sugar syrup', zh: '糖浆' },
    'Сахарная вата': { en: 'Cotton candy', zh: '棉花糖' },
    'Жжёный сахар': { en: 'Burnt sugar', zh: '焦糖' },
    'Сироп': { en: 'Syrup', zh: '糖浆' },
    'Кленовый сироп': { en: 'Maple syrup', zh: '枫糖浆' },
    'Патока': { en: 'Molasses', zh: '糖蜜' },
    'Светлая патока': { en: 'Light molasses', zh: '浅糖蜜' },
    'Чёрная патока': { en: 'Blackstrap molasses', zh: '黑糖蜜' },
    'Ваниль': { en: 'Vanilla', zh: '香草' },
    'Ванильные бобы': { en: 'Vanilla bean', zh: '香草荚' },
    'Натуральная ваниль': { en: 'Natural vanilla', zh: '天然香草' },
    'Ванильный крем': { en: 'Vanilla cream', zh: '香草奶油' },
    'Молочный': { en: 'Milky', zh: '奶香' },
    'Молоко': { en: 'Milk', zh: '牛奶' },
    'Молочно-кремовый': { en: 'Milky cream', zh: '奶油' },
    'Топлёное молоко': { en: 'Baked milk', zh: '炖奶' },
    'Сгущёнка': { en: 'Condensed milk', zh: '炼乳' },
    'Сгущённое молоко': { en: 'Condensed milk', zh: '炼乳' },
    'Крем': { en: 'Cream', zh: '奶油' },
    'Кремовый': { en: 'Creamy', zh: '奶油感' },
    'Сливка': { en: 'Cream', zh: '奶油' },
    'Сливочный': { en: 'Creamy', zh: '奶油味' },
    'Взбитые сливки': { en: 'Whipped cream', zh: '打发奶油' },
    'Тяжёлые сливки': { en: 'Heavy cream', zh: '厚奶油' },
    'Молочный крем': { en: 'Milk cream', zh: '奶乳' },
    'Карамелизированный крем': { en: 'Caramelised cream', zh: '焦化奶油' },
    'Кремовый сыр': { en: 'Cream cheese', zh: '奶油奶酪' },

    // ── Chocolate / coffee ───────────────────────────────────────────────────
    'Шоколадный': { en: 'Chocolate', zh: '巧克力' },
    'Горький шоколад': { en: 'Dark chocolate', zh: '黑巧克力' },
    'Молочный шоколад': { en: 'Milk chocolate', zh: '牛奶巧克力' },
    'Белый шоколад': { en: 'White chocolate', zh: '白巧克力' },
    'Какао': { en: 'Cocoa', zh: '可可' },
    'Какао-порошок': { en: 'Cocoa powder', zh: '可可粉' },
    'Какао-бобы': { en: 'Cocoa bean', zh: '可可豆' },
    'Горечь какао': { en: 'Cocoa bitterness', zh: '可可苦' },
    'Кофе': { en: 'Coffee', zh: '咖啡' },
    'Кофейный': { en: 'Coffee', zh: '咖啡香' },
    'Жареный кофе': { en: 'Roasted coffee', zh: '烘焙咖啡' },
    'Эспрессо': { en: 'Espresso', zh: '浓缩咖啡' },

    // ── Bread / roast ────────────────────────────────────────────────────────
    'Хлебный': { en: 'Bready', zh: '面包香' },
    'Свежий хлеб': { en: 'Fresh bread', zh: '新鲜面包' },
    'Жареный хлеб': { en: 'Toasted bread', zh: '烤面包' },
    'Поджаренный хлеб': { en: 'Toasted bread', zh: '烤面包' },
    'Тост': { en: 'Toast', zh: '吐司' },
    'Гренки': { en: 'Croutons', zh: '面包丁' },
    'Сухарь': { en: 'Rusk', zh: '面包干' },
    'Дрожжевое тесто': { en: 'Yeast dough', zh: '发面' },
    'Кислое тесто': { en: 'Sourdough', zh: '酸面团' },
    'Печенье': { en: 'Biscuit', zh: '饼干' },
    'Песочное печенье': { en: 'Shortbread', zh: '酥饼' },
    'Сдобное печенье': { en: 'Butter biscuit', zh: '黄油饼干' },
    'Овсяное печенье': { en: 'Oat biscuit', zh: '燕麦饼干' },
    'Попкорн': { en: 'Popcorn', zh: '爆米花' },
    'Обжаренный ячмень': { en: 'Roasted barley', zh: '烤大麦' },
    'Жареный': { en: 'Roasted', zh: '烘烤' },

    // ── Smoke / tobacco ──────────────────────────────────────────────────────
    'Копчёный': { en: 'Smoky', zh: '烟熏' },
    'Дым': { en: 'Smoke', zh: '烟' },
    'Лёгкий дым': { en: 'Light smoke', zh: '轻烟' },
    'Интенсивный дым': { en: 'Heavy smoke', zh: '浓烟' },
    'Копчёная древесина': { en: 'Smoked wood', zh: '烟熏木' },
    'Копчёная слива': { en: 'Smoked plum', zh: '烟熏李' },
    'Копчёный чай': { en: 'Smoked tea', zh: '烟熏茶' },
    'Табачный': { en: 'Tobacco', zh: '烟草' },
    'Свежий табак': { en: 'Fresh tobacco', zh: '鲜烟草' },
    'Трубочный табак': { en: 'Pipe tobacco', zh: '烟斗烟草' },
    'Сигарный лист': { en: 'Cigar leaf', zh: '雪茄叶' },
    'Кожа': { en: 'Leather', zh: '皮革' },

    // ── Marine ───────────────────────────────────────────────────────────────
    'Морской': { en: 'Marine', zh: '海洋' },
    'Морской воздух': { en: 'Sea air', zh: '海风' },
    'Солёный бриз': { en: 'Salty breeze', zh: '咸海风' },
    'Морская соль': { en: 'Sea salt', zh: '海盐' },
    'Чистая морская соль': { en: 'Clean sea salt', zh: '纯海盐' },
    'Солёный': { en: 'Salty', zh: '咸' },
    'Солёная вода': { en: 'Salt water', zh: '盐水' },
    'Водоросль': { en: 'Seaweed', zh: '海藻' },
    'Водорослевый': { en: 'Seaweed', zh: '海藻味' },
    'Свежая водоросль': { en: 'Fresh seaweed', zh: '鲜海藻' },
    'Сушёная водоросль': { en: 'Dried seaweed', zh: '干海藻' },
    'Нори': { en: 'Nori', zh: '海苔' },
    'Вакаме': { en: 'Wakame', zh: '裙带菜' },
    'Ламинария': { en: 'Kombu', zh: '昆布' },
    'Йод': { en: 'Iodine', zh: '碘' },
    'Йодистый': { en: 'Iodine', zh: '碘味' },
    'Свежая рыба': { en: 'Fresh fish', zh: '鲜鱼' },

    // ── Vegetal ──────────────────────────────────────────────────────────────
    'Овощной': { en: 'Vegetal', zh: '蔬菜' },
    'Шпинат': { en: 'Spinach', zh: '菠菜' },
    'Шпинат и варёная зелень': { en: 'Spinach and cooked greens', zh: '菠菜与熟青菜' },
    'Варёная зелень': { en: 'Cooked greens', zh: '熟青菜' },
    'Брокколи': { en: 'Broccoli', zh: '西兰花' },
    'Спаржа': { en: 'Asparagus', zh: '芦笋' },
    'Сельдерей': { en: 'Celery', zh: '芹菜' },
    'Тыква': { en: 'Pumpkin', zh: '南瓜' },
    'Томат': { en: 'Tomato', zh: '番茄' },
    'Томатный лист': { en: 'Tomato leaf', zh: '番茄叶' },
    'Свекла': { en: 'Beetroot', zh: '甜菜' },
    'Свекольный': { en: 'Beetroot', zh: '甜菜味' },
    'Свежая свёкла': { en: 'Fresh beetroot', zh: '鲜甜菜' },
    'Запечённая свёкла': { en: 'Baked beetroot', zh: '烤甜菜' },
    'Горох и бобовые': { en: 'Peas and legumes', zh: '豌豆与豆类' },
    'Бобовые': { en: 'Legumes', zh: '豆类' },
    'Сырой картофель': { en: 'Raw potato', zh: '生土豆' },
    'Сухой лист': { en: 'Dry leaf', zh: '干叶' },

    // ── Mushroom / umami ─────────────────────────────────────────────────────
    'Грибы': { en: 'Mushroom', zh: '蘑菇' },
    'Грибной': { en: 'Mushroom', zh: '菌香' },
    'Грибной бульон': { en: 'Mushroom broth', zh: '蘑菇汤' },
    'Белый гриб': { en: 'Porcini', zh: '牛肝菌' },
    'Подосиновик': { en: 'Birch bolete', zh: '红菇' },
    'Шиитаке': { en: 'Shiitake', zh: '香菇' },
    'Умами': { en: 'Umami', zh: '鲜味' },
    'Бульонный': { en: 'Brothy', zh: '汤感' },
    'Мясной бульон': { en: 'Meat broth', zh: '肉汤' },
    'Костный бульон': { en: 'Bone broth', zh: '骨汤' },
    'Солёный бульон': { en: 'Savoury broth', zh: '咸汤' },
    'Мисо': { en: 'Miso', zh: '味噌' },
    'Соевый': { en: 'Soy', zh: '豆香' },
    'Соевый соус': { en: 'Soy sauce', zh: '酱油' },
    'Ферментированные бобы': { en: 'Fermented beans', zh: '发酵豆' },

    // ── Fermented / aged ─────────────────────────────────────────────────────
    'Ферментированный': { en: 'Fermented', zh: '发酵' },
    'Ферментированные ягоды': { en: 'Fermented berries', zh: '发酵浆果' },
    'Квашеный': { en: 'Pickled', zh: '腌渍' },
    'Бражка': { en: 'Mash', zh: '酒醪' },
    'Винный': { en: 'Winey', zh: '酒香' },
    'Красное вино': { en: 'Red wine', zh: '红酒' },
    'Белое вино': { en: 'White wine', zh: '白葡萄酒' },
    'Спиртовой': { en: 'Alcoholic', zh: '酒精' },
    'Старый склад': { en: 'Old warehouse', zh: '老仓味' },
    'Затхлый': { en: 'Musty', zh: '仓味' },
    'Плесень': { en: 'Mould', zh: '霉味' },
    'Сырость': { en: 'Dampness', zh: '潮味' },
    'Пыль': { en: 'Dust', zh: '尘味' },
    'Картон': { en: 'Cardboard', zh: '纸板味' },
    'Бумага': { en: 'Paper', zh: '纸味' },
    'Целлюлоза': { en: 'Cellulose', zh: '纤维素' },

    // ── Animal ───────────────────────────────────────────────────────────────
    'Животный': { en: 'Animalic', zh: '动物香' },
    'Мускус': { en: 'Musk', zh: '麝香' },
    'Шерсть': { en: 'Wool', zh: '羊毛' },
    'Конюшня': { en: 'Stable', zh: '马厩' },

    // ── Camphor / cooling ────────────────────────────────────────────────────
    'Камфорный': { en: 'Camphor', zh: '樟香' },
    'Камфора': { en: 'Camphor', zh: '樟脑' },
    'Камфорная мазь': { en: 'Camphor balm', zh: '樟脑膏' },
    'Камфорный ментол': { en: 'Camphor menthol', zh: '樟脑薄荷' },
    'Лёгкая камфора': { en: 'Light camphor', zh: '淡樟香' },
    'Интенсивная камфора': { en: 'Strong camphor', zh: '浓樟香' },
    'Борнеол': { en: 'Borneol', zh: '冰片' },
    'Ментол': { en: 'Menthol', zh: '薄荷脑' },
    'Ментоловый/Охлаждающий': { en: 'Menthol / cooling', zh: '薄荷／清凉' },
    'Свежий ментол': { en: 'Fresh menthol', zh: '鲜薄荷脑' },
    'Лёгкий ментол': { en: 'Light menthol', zh: '淡薄荷脑' },

    // ── Pharmacy ─────────────────────────────────────────────────────────────
    'Аптечный': { en: 'Medicinal', zh: '药香' },
    'Хинин': { en: 'Quinine', zh: '奎宁' },
    'Грейпфрутовый хинин': { en: 'Grapefruit quinine', zh: '西柚奎宁' },
    'Тоник': { en: 'Tonic', zh: '汤力水' },

    // ── Structure / mouthfeel ────────────────────────────────────────────────
    'Горький': { en: 'Bitter', zh: '苦' },
    'Лёгкая горечь': { en: 'Light bitterness', zh: '微苦' },
    'Кислый': { en: 'Sour', zh: '酸' },
    'Зелёная кислота': { en: 'Green acidity', zh: '青酸' },
    'Вяжущий': { en: 'Astringent', zh: '涩' },
    'Терпкий': { en: 'Tart', zh: '收敛' },
    'Дубильный': { en: 'Tannic', zh: '单宁' },
    'Танины чёрного чая': { en: 'Black tea tannins', zh: '红茶单宁' },
    'Кисельно-терпкий': { en: 'Thick and tart', zh: '稠涩' },

    // ── Category roots and catch-alls ────────────────────────────────────────
    'Другое': { en: 'Other', zh: '其他' },
    'Произвольное описание': { en: 'Free description', zh: '自由描述' },
};

// The stored Russian value is the fallback: a descriptor added to the seeder but
// not yet translated shows in Russian rather than vanishing.
const translateDescriptor = (term, locale) => {
    if (!term || locale === 'ru') return term;
    const entry = DESCRIPTORS[term];
    return (entry && entry[locale]) || term;
};

// A full "Цветочный → Жасмин" path, translated stage by stage.
const translateDescriptorPath = (path, locale) => {
    if (!path || locale === 'ru') return path;
    return path.split(' → ').map((p) => translateDescriptor(p, locale)).join(' → ');
};

module.exports = { DESCRIPTORS, translateDescriptor, translateDescriptorPath };
